spring:
  datasource:
    url: jdbc:postgresql://localhost:3307/userservice
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-plateform: org.hibernate.dialect.PostgreSQLDialect


    url: jdbc:postgresql://localhost:3307/notificationservice
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver




management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus   # expose actuator endpoints
  tracing:
    sampling:
      probability: 1.0   # 100% sample (reduce in prod)
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
springdoc:
  swagger-ui:
    path: /swagger-ui.html
