
management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus   # expose actuator endpoints
  tracing:
    sampling:
      probability: 1.0   # 100% sample (reduce in prod)
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
springdoc:
  swagger-ui:
    path: /swagger-ui.html
